### ISSUE TITLE
Datenrecherche & -beschaffung

### ISSUE THREAD

**Issue by guntherbuffet** [tuwien-geoweb-2015/g08_p15#2]
Download von touristisch relevanten Informationen und Daten(sätzen) von data.gv.at und open.wien.gv.at und lokal sichern.

**Comment by Hoebi** [comment]
Punkt-Layer:
Gebetshäuser in Wien
Adventmärkte in Wien
Öffentliche Toiletten
Weltkulturerbeflächen in Wien
Parkanlagen
Museen in Wien
Burgen und Schlösser

Vielleicht:
https://www.data.gv.at/datensatz/?id=898afe8c-0297-45d6-b4b5-0cb9e632094b

Links zu Fehlenden Toppics
Parkpickerl: https://www.data.gv.at/katalog/dataset/71a6ca86-228a-4b57-b1bc-c3b887dd009e
Fuzo: https://www.data.gv.at/katalog/dataset/946a1d1c-27ea-49d4-93be-9ac68b399a20
Radwege (+Straßen): https://www.data.gv.at/katalog/dataset/5e6175cd-dc44-4b32-a64a-1ac4239a6e4a
Themen Radwege: https://www.data.gv.at/katalog/dataset/ff99d26f-8176-4c81-a60c-dfc0bf9a226c
Bev. nach Land Zählbezirk: https://www.data.gv.at/katalog/dataset/78ff4a79-5942-4254-ae3d-567fae3c9db7

**Comment by guntherbuffet** [comment]
data acquisition check
